import { Job } from "./types";

export const SAMPLE_JOBS: Job[] = [
  {
    id: "sm-01",
    title: "Senior Machine Learning Engineer",
    company: "Infosys AI Cloud",
    location: "Bangalore",
    workType: "WFO",
    description: "Design and implement scalable machine learning models for enterprise financial analytics. Optimize deep learning pipelines on AWS and Azure cloud platforms.",
    skills: ["Python", "PyTorch", "TensorFlow", "AWS", "Kubernetes", "SQL"],
    salaryRange: "₹24,00,000 - ₹32,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-12",
    portalSource: "Naukri",
    applyUrl: "https://www.naukri.com"
  },
  {
    id: "sm-02",
    title: "AI Specialist (Computer Vision & NLP)",
    company: "TCS Research & Innovation",
    location: "Kochi",
    workType: "Hybrid",
    description: "Develop novel computer vision algorithms and custom NLP transformers for automated industrial manufacturing inspection. Work directly with state-of-the-art vision models.",
    skills: ["OpenCV", "Transformers", "Python", "PyTorch", "HuggingFace", "YOLO"],
    salaryRange: "₹14,00,000 - ₹20,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-03",
    title: "Generative AI Research Engineer",
    company: "Cognizant Technology Solutions",
    location: "Kochi",
    workType: "WFO",
    description: "Build cutting-edge Retrieval-Augmented Generation (RAG) applications using LLMs. Finetune open-source models (Llama-3, Mistral) for secure cloud databases.",
    skills: ["Llama-3", "LangChain", "Vector DBs", "Python", "LlamaIndex", "Docker"],
    salaryRange: "₹12,00,000 - ₹18,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-12",
    portalSource: "Indeed India",
    applyUrl: "https://www.indeed.com"
  },
  {
    id: "sm-04",
    title: "Data Scientist - LLM Fine-Tuning",
    company: "Ola Electric AI Labs",
    location: "Bangalore",
    workType: "WFO",
    description: "Train and evaluate LLM agents for autonomous riding intelligence and vehicle telematics feedback loops. Fine-tune pre-trained models on specialized automotive datasets.",
    skills: ["Python", "LLMs", "Qlora", "Deep Learning", "TensorFlow", "CUDA"],
    salaryRange: "₹28,00,000 - ₹38,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-10",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-05",
    title: "Lead AI Research Scientist",
    company: "Wipro AI Labs",
    location: "Hyderabad",
    workType: "Hybrid",
    description: "Lead conversational AI research and direct multi-agent systems optimization. Support product engineering groups with architectural blueprints for edge deployments.",
    skills: ["Research Architecture", "PyTorch", "NLP", "BERT", "Multi-Agent Systems"],
    salaryRange: "₹35,00,000 - ₹48,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-13",
    portalSource: "Naukri",
    applyUrl: "https://www.naukri.com"
  },
  {
    id: "sm-06",
    title: "Junior NLP Data Annotator & Engineer",
    company: "Tech Mahindra AI",
    location: "Mumbai",
    workType: "Remote",
    description: "Validate LLM response pipelines, set up high-quality vector database indexing, and write clean python validation scripts to keep response models secure and unbiased.",
    skills: ["Python", "SQL", "NLP", "Data Cleaning", "Pandas", "GitHub"],
    salaryRange: "₹6,00,000 - ₹9,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-12",
    portalSource: "Indeed India",
    applyUrl: "https://www.indeed.com"
  },
  {
    id: "sm-07",
    title: "MLOps Engineer (CI/CD for ML Models)",
    company: "Swiggy Enterprise Group",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Orchestrate end-to-end model training to deployment lifecycle using Kubeflow, MLflow, and SageMaker. Accelerate CI/CD cycles for food delivery recommendation algorithms.",
    skills: ["MLflow", "Docker", "Kubernetes", "AWS SageMaker", "Jenkins", "Python"],
    salaryRange: "₹18,00,000 - ₹25,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-09",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-08",
    title: "NLP Software Engineer",
    company: "EY Global Delivery Services",
    location: "Kochi",
    workType: "WFO",
    description: "Incorporate semantic search, smart categorization, and automatic parsing into internal ERP dashboards. Experience with scikit-learn, HuggingFace, and spaCy is required.",
    skills: ["spaCy", "Transformers", "NLP", "Python", "Flask", "PostgreSQL"],
    salaryRange: "₹9,00,000 - ₹14,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-09",
    title: "Compiler Optimizations Specialist for ML",
    company: "Intel Technology India",
    location: "Bangalore",
    workType: "WFO",
    description: "Write custom kernels and performance compilation patches for AI hardware accelerators. Work on LLVM, TVM, and OpenVINO optimization backends.",
    skills: ["C++", "CUDA", "LLVM", "TVM", "PyTorch Core", "Hardware Architecture"],
    salaryRange: "₹30,00,000 - ₹42,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-08",
    portalSource: "Company Portal",
    applyUrl: "https://jobs.intel.com"
  },
  {
    id: "sm-10",
    title: "Associate AI Product Engineer",
    company: "Sigmoid AI Analytics",
    location: "Remote",
    workType: "Remote",
    description: "Integrate LLM API backends into highly responsive React user boards. Implement client telemetry, state synchronization, and error-handling fallbacks for complex visual graphs.",
    skills: ["React", "TypeScript", "Node.js", "Express", "REST APIs", "Tailwind CSS"],
    salaryRange: "₹8,00,000 - ₹12,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-13",
    portalSource: "Indeed India",
    applyUrl: "https://www.indeed.com"
  },
  {
    id: "sm-11",
    title: "Deep Learning Engineer (Speech Synthesis)",
    company: "Reliance Jio Platforms",
    location: "Mumbai",
    workType: "Hybrid",
    description: "Train multi-lingual Indian speech synthesis models. Adapt modern models for Hindi, Marathi, Tamil, Malayalam, and Telugu edge deployments on mobile.",
    skills: ["PyTorch", "Speech Synthesis", "WaveNet", "FastSpeech", "Kaldi", "Python"],
    salaryRange: "₹18,00,000 - ₹26,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-13",
    portalSource: "Naukri",
    applyUrl: "https://www.naukri.com"
  },
  {
    id: "sm-12",
    title: "AI & ML Consultant",
    company: "PwC India",
    location: "Delhi NCR",
    workType: "WFO",
    description: "Advise enterprise healthcare clients on secure deployment models for diagnostic prediction models and medical data processing compliance pipelines.",
    skills: ["Predictive Modeling", "Healthcare AI", "Python", "Statsmodels", "Strategy"],
    salaryRange: "₹16,00,000 - ₹22,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "Naukri",
    applyUrl: "https://www.naukri.com"
  },
  {
    id: "sm-13",
    title: "Principal Machine Learning Engineer",
    company: "Flipkart AI Group",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Architect and lead the recommendation systems group. Scale transaction tracking, collaborative filtering, and generative customer query matching systems serving 100M+ users.",
    skills: ["PyTorch", "Scala", "Spark", "Redis", "TensorFlow", "Kubernetes"],
    salaryRange: "₹45,00,000 - ₹62,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-12",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-14",
    title: "NLP Research Specialist",
    company: "Microsoft Research India",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Advance cross-lingual translation research for lower-resource Indian vernaculars. Author papers and build proof-of-concept multi-lingual transformers.",
    skills: ["Transformers", "Research", "PyTorch", "Machine Translation", "BERT"],
    salaryRange: "₹38,00,000 - ₹50,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-12",
    portalSource: "Company Portal",
    applyUrl: "https://careers.microsoft.com"
  },
  {
    id: "sm-15",
    title: "AI Developer - Computer Vision Specialist",
    company: "UST Global",
    location: "Kochi",
    workType: "WFO",
    description: "Create visual inspection AI modules for global retail giants. Implement edge-device inference, camera telemetry parsing, and custom object classification models.",
    skills: ["OpenCV", "TensorRT", "YOLO", "C++", "Python", "MQTT"],
    salaryRange: "₹10,00,000 - ₹15,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-09",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-16",
    title: "Generative AI Application Architect",
    company: "HCLTech",
    location: "Chennai",
    workType: "Hybrid",
    description: "Design multi-agent task automation frameworks using LangGraph and AutoGen for enterprise logistics. Implement guardrails around sensitive prompt inputs.",
    skills: ["LangGraph", "Python", "FastAPI", "OpenAI API", "Redis", "Azure AD"],
    salaryRange: "₹22,00,000 - ₹30,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-11",
    portalSource: "Naukri",
    applyUrl: "https://www.naukri.com"
  },
  {
    id: "sm-17",
    title: "Data Scientist (AI & Predictive Analytics)",
    company: "Acme Analytics",
    location: "Kochi",
    workType: "Remote",
    description: "Build robust statistical prediction models for supply chain forecasting. Run regressions, time-series forecasting, and XGBoost anomaly detection.",
    skills: ["XGBoost", "Python", "Pandas", "Scikit-Learn", "Statsmodels", "Docker"],
    salaryRange: "₹8,00,000 - ₹13,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-13",
    portalSource: "Indeed India",
    applyUrl: "https://www.indeed.com"
  },
  {
    id: "sm-18",
    title: "Machine Learning Intern",
    company: "Razorpay AI",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Assist the fraud risk analytics team in drafting feature-engineering pipelines and writing SQL aggregation models for payment fraud prevention systems.",
    skills: ["Python", "SQL", "Pandas", "Scikit-Learn", "Jupyter Notebook"],
    salaryRange: "₹6,00,000 - ₹8,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-13",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-19",
    title: "AI Engineer - Financial Trading Tools",
    company: "Kolkata Algorithmic Trade Lab",
    location: "Kolkata",
    workType: "WFO",
    description: "Implement reinforcement learning models for high-frequency stock signal generation and asset portfolio risk index scoring.",
    skills: ["Reinforcement Learning", "Python", "Pandas", "C++", "Keras"],
    salaryRange: "₹18,00,000 - ₹26,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "Naukri",
    applyUrl: "https://www.naukri.com"
  },
  {
    id: "sm-20",
    title: "Computer Vision Researcher (Senior Role)",
    company: "Samsung R&D India",
    location: "Delhi NCR",
    workType: "Hybrid",
    description: "Optimize neural graphic processors and semantic segmentation neural nets for cameras on next-generation smart devices. Publish papers at top venues.",
    skills: ["PyTorch", "C++", "NeRF", "Segmentation", "Mobile GPU Optimization"],
    salaryRange: "₹34,00,000 - ₹46,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-10",
    portalSource: "Company Portal",
    applyUrl: "https://careers.samsung.com"
  },
  {
    id: "sm-21",
    title: "Lead ML Systems Architect",
    company: "Adobe Systems India",
    location: "Pune",
    workType: "Hybrid",
    description: "Lead the vector modeling backend for enterprise creative tools. Maximize GPU parallelization, tensor compilation runtimes, and caching optimization grids.",
    skills: ["PyTorch Core", "CUDA", "C++", "GPU Performance", "Docker", "Triton"],
    salaryRange: "₹42,00,000 - ₹58,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-12",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-22",
    title: "NLP Developer - Chatbot Specialist",
    company: "Cognizant Technology Solutions",
    location: "Chennai",
    workType: "WFO",
    description: "Build conversation trees, multi-lingual agent routers, and semantic fallback APIs for large consumer telecoms using enterprise huggingface models.",
    skills: ["HuggingFace", "Python", "Rasa", "FastAPI", "Docker"],
    salaryRange: "₹11,00,000 - ₹16,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-12",
    portalSource: "Naukri",
    applyUrl: "https://www.naukri.com"
  },
  {
    id: "sm-23",
    title: "Undergraduate AI Research Associate",
    company: "IIT Madras Research Park",
    location: "Chennai",
    workType: "Hybrid",
    description: "Work on public healthcare digital datasets to build predictive diagnostics models using advanced spatial regression and GNNs.",
    skills: ["Python", "PyTorch Geometric", "GNNs", "GIS Data", "Pandas"],
    salaryRange: "₹7,00,000 - ₹10,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://www.linkedin.com"
  },
  {
    id: "sm-24",
    title: "Machine Learning Consultant",
    company: "Deloitte India",
    location: "Pune",
    workType: "WFO",
    description: "Conduct security, audit compliance, and bias assessments on automated predictive models deployed by retail banking consortia in Pune.",
    skills: ["AI Auditing", "Explainable AI", "Python", "SHAP", "Model Interpretability"],
    salaryRange: "₹15,00,000 - ₹21,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-12",
    portalSource: "Company Portal",
    applyUrl: "https://careers.deloitte.com"
  },
  {
    id: "sm-25",
    title: "Senior Prompt Engineer (AI Alignment)",
    company: "InMobi",
    location: "Bangalore",
    workType: "Remote",
    description: "Develop, review, and automate optimal generative prompt sequences to support fast automated copy-writing grids and marketing content filters.",
    skills: ["Prompt Engineering", "LLM Evaluation", "GPT-4", "Claude", "Python", "HTML"],
    salaryRange: "₹16,00,000 - ₹24,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-13",
    portalSource: "Indeed India",
    applyUrl: "https://www.indeed.com"
  },
  {
    id: "sm-26",
    title: "AI Infrastructure Specialist",
    company: "Reliance Jio Infocomm",
    location: "Mumbai",
    workType: "WFO",
    description: "Build and scale high-performance GPU cluster virtualization for deep learning training payloads. Setup high-throughput distributed memory caches for video indexing.",
    skills: ["GPUs", "Docker", "NVIDIA CUDA", "Linux", "PyTorch", "Network Tuning"],
    salaryRange: "₹22,00,000 - ₹30,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-14",
    portalSource: "Naukri",
    applyUrl: "https://www.jio.com"
  },
  {
    id: "sm-27",
    title: "Deep Learning Engineer",
    company: "Acko General Insurance",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Develop predictive computer vision frameworks to automate vehicle damage evaluation from user images. Deploy optimized models to resource-constrained environments.",
    skills: ["Computer Vision", "TensorFlow", "FastAPI", "Python", "OpenCV", "GCP"],
    salaryRange: "₹15,00,000 - ₹22,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-12",
    portalSource: "LinkedIn",
    applyUrl: "https://www.acko.com"
  },
  {
    id: "sm-28",
    title: "Machine Learning Intern",
    company: "Zoho Corporation",
    location: "Chennai",
    workType: "WFO",
    description: "Assist in developing intelligent auto-complete and predictive CRM assistance modules. Conduct intensive quantitative experiments with compact sentiment analysis networks.",
    skills: ["Python", "Scikit-Learn", "Pandas", "NLP", "Git"],
    salaryRange: "₹5,00,000 - ₹8,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-13",
    portalSource: "Company Portal",
    applyUrl: "https://www.zoho.com"
  },
  {
    id: "sm-29",
    title: "Generative AI Architect",
    company: "Tech Mahindra",
    location: "Hyderabad",
    workType: "Hybrid",
    description: "Consult with Fortune 500 clients to design and prototype robust secure agent patterns, hybrid on-prem / cloud model setups, and safety rails using Guardrails AI.",
    skills: ["Generative AI", "Azure OpenAI", "LlamaIndex", "Security", "FastAPI"],
    salaryRange: "₹38,00,000 - ₹50,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://www.techmahindra.com"
  },
  {
    id: "sm-30",
    title: "Robotics & Computer Vision Specialist",
    company: "GreyOrange Robotics",
    location: "Delhi NCR",
    workType: "WFO",
    description: "Develop autonomous warehouse robotic navigation systems. Focus on real-time stereo-vision, edge feature map synthesis, and sensor fusion filters.",
    skills: ["Computer Vision", "ROS", "C++", "Python", "LiDAR", "Stereo Vision"],
    salaryRange: "₹25,00,000 - ₹35,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-11",
    portalSource: "Naukri",
    applyUrl: "https://www.greyorange.com"
  },
  {
    id: "sm-31",
    title: "Junior Data Scientist (NLP)",
    company: "Freshworks AI division",
    location: "Chennai",
    workType: "Remote",
    description: "Perform exploratory data analysis on conversational support logs and fine-tune classifiers for multilingual ticket sorting. Assist senior engineers with pipeline validation.",
    skills: ["Python", "Pandas", "NLTK", "Scikit-Learn", "HuggingFace"],
    salaryRange: "₹8,50,000 - ₹12,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-13",
    portalSource: "Indeed India",
    applyUrl: "https://www.freshworks.com"
  },
  {
    id: "sm-32",
    title: "Director of Artificial Intelligence",
    company: "HDFC Bank Advanced Tech Hub",
    location: "Mumbai",
    workType: "WFO",
    description: "Orchestrate HDFC Bank's multi-hub AI strategy. Oversee large divisions of modelers, MLOps specialists, chatbot architects, and audit compliance advisors.",
    skills: ["AI Strategy", "Executive Leadership", "SaaS", "Fintech Compliance", "Budgeting"],
    salaryRange: "₹60,00,000 - ₹85,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://www.hdfcbank.com"
  },
  {
    id: "sm-33",
    title: "AI Product Manager",
    company: "Google India",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Lead the roadmap for enterprise generative AI features across Google Workspace. Work with engineering, UX, and marketing teams to deliver AI products.",
    skills: ["Product Management", "Generative AI", "Agile", "Strategy", "User Experience"],
    salaryRange: "₹40,00,000 - ₹55,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-13",
    portalSource: "Google Careers",
    applyUrl: "https://careers.google.com"
  },
  {
    id: "sm-34",
    title: "Applied AI Scientist",
    company: "Amazon Web Services",
    location: "Hyderabad",
    workType: "WFO",
    description: "Build and deploy large-scale forecasting models for Amazon's supply chain. Requires deep knowledge of time series analysis and stochastic modeling.",
    skills: ["Forecasting", "Python", "AWS", "Deep Learning", "TensorFlow"],
    salaryRange: "₹35,00,000 - ₹48,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://amazon.jobs"
  },
  {
    id: "sm-35",
    title: "Junior Data Engineer",
    company: "TVS Motor Company",
    location: "Chennai",
    workType: "WFO",
    description: "Develop big data pipelines to manage IoT telemetry from connected vehicles. Support the predictive maintenance team with cleaned, structured datasets.",
    skills: ["SQL", "Python", "Spark", "Data Engineering", "AWS"],
    salaryRange: "₹6,50,000 - ₹9,50,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-12",
    portalSource: "Naukri",
    applyUrl: "https://www.tvsmotor.com"
  },
  {
    id: "sm-36",
    title: "Machine Learning Researcher - Healthcare",
    company: "Siemens Healthineers",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Research and implement novel 3D segmentation algorithms for MRI/CT scans. Optimize inference speed for real-time surgical assistance systems.",
    skills: ["Medical Imaging", "PyTorch", "Monai", "Computer Vision", "3D Segmentation"],
    salaryRange: "₹20,00,000 - ₹28,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-10",
    portalSource: "Indeed India",
    applyUrl: "https://jobs.siemens.com"
  },
  {
    id: "sm-37",
    title: "Sr. AI/ML Engineer",
    company: "Cisco Systems",
    location: "Bangalore",
    workType: "WFO",
    description: "Design AI-driven network anomaly detection algorithms. Integrate real-time ML inference into hardware networking switches and routers.",
    skills: ["Networking", "C++", "Python", "Anomaly Detection", "Machine Learning"],
    salaryRange: "₹28,00,000 - ₹38,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-11",
    portalSource: "LinkedIn",
    applyUrl: "https://jobs.cisco.com"
  },
  {
    id: "sm-38",
    title: "Conversational AI Developer",
    company: "Mindtree",
    location: "Pune",
    workType: "Remote",
    description: "Build virtual assistants and voice bots using Dialogflow and Rasa for telecom sector clients. Implement backend logic in Node.js.",
    skills: ["Dialogflow", "Rasa", "Node.js", "Python", "NLP"],
    salaryRange: "₹9,00,000 - ₹14,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-13",
    portalSource: "Naukri",
    applyUrl: "https://www.mindtree.com"
  },
  {
    id: "sm-39",
    title: "Director, Data Science",
    company: "Ola Cabs",
    location: "Bangalore",
    workType: "WFO",
    description: "Head the dynamic pricing and routing optimization data science teams. Set the technical vision and manage a group of 30+ data scientists and engineers.",
    skills: ["Leadership", "Operations Research", "Machine Learning", "Strategy", "Pricing Algorithms"],
    salaryRange: "₹70,00,000 - ₹90,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://ola.com"
  },
  {
    id: "sm-40",
    title: "Machine Learning Intern",
    company: "Paytm",
    location: "Delhi NCR",
    workType: "Hybrid",
    description: "Work with the risk team to evaluate alternative credit scoring models. Learn how to deploy ML models using internal MLOps tooling.",
    skills: ["Python", "SQL", "Scikit-Learn", "Data Analysis"],
    salaryRange: "₹4,00,000 - ₹6,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-12",
    portalSource: "Company Portal",
    applyUrl: "https://paytm.com"
  },
  {
    id: "sm-41",
    title: "Robotics Perception Engineer",
    company: "Wipro",
    location: "Hyderabad",
    workType: "WFO",
    description: "Develop sensor fusion algorithms (Lidar + Camera + Radar) for autonomous drone navigation and obstacle avoidance in complex environments.",
    skills: ["C++", "ROS", "Sensor Fusion", "Kalman Filters", "Computer Vision"],
    salaryRange: "₹18,00,000 - ₹25,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-09",
    portalSource: "Naukri",
    applyUrl: "https://www.wipro.com"
  },
  {
    id: "sm-42",
    title: "AI Cloud Architect",
    company: "IBM India",
    location: "Mumbai",
    workType: "Hybrid",
    description: "Design multi-cloud architecture for enterprise AI deployments. Ensure high-availability and optimize infrastructure costs for training large models.",
    skills: ["IBM Cloud", "AWS", "Azure", "Kubernetes", "Architecture", "MLOps"],
    salaryRange: "₹30,00,000 - ₹42,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-13",
    portalSource: "LinkedIn",
    applyUrl: "https://careers.ibm.com"
  },
  {
    id: "sm-43",
    title: "NLP Engineer - Vernacular Languages",
    company: "ShareChat",
    location: "Bangalore",
    workType: "Remote",
    description: "Build robust machine translation and sentiment analysis models for 15+ Indian regional languages. Manage large-scale custom web-crawled datasets.",
    skills: ["NLP", "Transformers", "Python", "PyTorch", "Multilingual ML"],
    salaryRange: "₹20,00,000 - ₹30,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-14",
    portalSource: "Company Portal",
    applyUrl: "https://sharechat.com"
  },
  {
    id: "sm-44",
    title: "ML Quantitative Analyst",
    company: "JPMorgan Chase & Co.",
    location: "Mumbai",
    workType: "WFO",
    description: "Use deep learning and statistical methods to uncover signals in alternative datasets for algorithmic trading. Strong mathematical background is a must.",
    skills: ["Quantitative Analysis", "Deep Learning", "Python", "C++", "Finance"],
    salaryRange: "₹35,00,000 - ₹50,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-10",
    portalSource: "LinkedIn",
    applyUrl: "https://jobs.jpmorganchase.com"
  },
  {
    id: "sm-45",
    title: "Data Annotator & Prompt Writer",
    company: "Scale AI",
    location: "Remote",
    workType: "Remote",
    description: "Create high-quality RLHF datasets for state-of-the-art LLMs. Write creative stories, debug code, and meticulously follow complex formatting guidelines.",
    skills: ["Writing", "Attention to Detail", "English", "Logic", "Content Creation"],
    salaryRange: "₹4,00,000 - ₹6,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-14",
    portalSource: "Indeed India",
    applyUrl: "https://scale.com"
  },
  {
    id: "sm-46",
    title: "Vice President, AI Engineering",
    company: "MakeMyTrip",
    location: "Delhi NCR",
    workType: "Hybrid",
    description: "Lead the AI engineering division to transform user travel experiences with personalized GenAI itineraries and dynamic real-time flight pricing algorithms.",
    skills: ["Executive Leadership", "Engineering Management", "AI Strategy", "E-commerce"],
    salaryRange: "₹60,00,000 - ₹90,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-11",
    portalSource: "LinkedIn",
    applyUrl: "https://careers.makemytrip.com"
  },
  {
    id: "sm-47",
    title: "GenAI Full-Stack Developer",
    company: "Infosys",
    location: "Pune",
    workType: "Hybrid",
    description: "Develop full-stack web applications featuring integrated LLM chatbots and semantic search. Requires strong React and API development skills.",
    skills: ["React", "Node.js", "Python", "LangChain", "SQL", "Tailwind CSS"],
    salaryRange: "₹12,00,000 - ₹18,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-13",
    portalSource: "Naukri",
    applyUrl: "https://www.infosys.com"
  },
  {
    id: "sm-48",
    title: "Founding AI Engineer",
    company: "Stealth GenAI Startup",
    location: "Bangalore",
    workType: "WFO",
    description: "Join as the first engineering hire. End-to-end responsibility of building an AI sales co-pilot from concept to production. Equity offered.",
    skills: ["Startups", "Full-Stack AI", "Python", "React", "AWS", "Product Building"],
    salaryRange: "₹25,00,000 - ₹40,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-14",
    portalSource: "AngelList (Wellfound)",
    applyUrl: "https://wellfound.com"
  },
  {
    id: "sm-49",
    title: "AI Ethics & Policy Researcher",
    company: "Tata Consultancy Services",
    location: "Chennai",
    workType: "Hybrid",
    description: "Develop frameworks to evaluate AI systems for fairness, bias, and regulatory compliance (e.g., EU AI Act, India DPDP). Publish industry whitepapers.",
    skills: ["AI Ethics", "Policy Research", "Law", "Tech Writing", "Auditing"],
    salaryRange: "₹14,00,000 - ₹22,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-12",
    portalSource: "LinkedIn",
    applyUrl: "https://www.tcs.com"
  },
  {
    id: "sm-50",
    title: "AI Customer Success Engineer",
    company: "Anthropic",
    location: "Remote",
    workType: "Remote",
    description: "Help enterprise customers successfully integrate Claude into their applications. Write customized prompt templates and debug integration code.",
    skills: ["Customer Success", "Python", "Prompt Engineering", "Communication", "APIs"],
    salaryRange: "₹25,00,000 - ₹40,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-13",
    portalSource: "Company Portal",
    applyUrl: "https://anthropic.com/careers"
  },
  {
    id: "sm-51",
    title: "Senior CV Engineer (Defect Detection)",
    company: "Bosch India",
    location: "Bangalore",
    workType: "WFO",
    description: "Implement high-speed machine vision systems for manufacturing defect detection on assembly lines. Work closely with hardware engineering teams.",
    skills: ["Machine Vision", "OpenCV", "C++", "PyTorch", "Manufacturing IoT"],
    salaryRange: "₹24,00,000 - ₹34,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-09",
    portalSource: "LinkedIn",
    applyUrl: "https://careers.bosch.com"
  },
  {
    id: "sm-52",
    title: "Data Science Trainee",
    company: "Fractal Analytics",
    location: "Mumbai",
    workType: "Hybrid",
    description: "Participate in a 6-month intensive training program covering statistical modeling, data engineering, and introductory machine learning techniques.",
    skills: ["Python", "Mathematics", "Statistics", "SQL", "Problem Solving"],
    salaryRange: "₹5,00,000 - ₹7,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-14",
    portalSource: "Campus Placements/Direct",
    applyUrl: "https://fractal.ai"
  },
  {
    id: "sm-53",
    title: "Head of AI Infrastructure",
    company: "PhonePe",
    location: "Bangalore",
    workType: "WFO",
    description: "Scale PhonePe's machine learning cluster infrastructure. Manage multi-petabyte data lakes and design robust, low-latency API serving platforms.",
    skills: ["Infrastructure", "Kubernetes", "Hadoop/Spark", "System Design", "Leadership"],
    salaryRange: "₹65,00,000 - ₹85,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-10",
    portalSource: "LinkedIn",
    applyUrl: "https://www.phonepe.com"
  },
  {
    id: "sm-54",
    title: "Machine Learning Test Engineer",
    company: "Capgemini",
    location: "Pune",
    workType: "Hybrid",
    description: "Design automated test suites for assessing machine learning model accuracy, robustness, and drift over time. Integrate QA metrics into the CI/CD pipeline.",
    skills: ["Software Testing", "Python", "Pytest", "MLOps", "QA"],
    salaryRange: "₹8,00,000 - ₹12,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "Naukri",
    applyUrl: "https://www.capgemini.com"
  },
  {
    id: "sm-55",
    title: "Senior MLOps Architect",
    company: "LTIMindtree",
    location: "Chennai",
    workType: "WFO",
    description: "Define the standardized MLOps architecture blue-print for all global enterprise clients. Evaluate and select optimum ML tooling vendors.",
    skills: ["MLOps Blueprinting", "Architecture", "Cloud Native", "Kubeflow", "MLflow"],
    salaryRange: "₹38,00,000 - ₹50,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-12",
    portalSource: "LinkedIn",
    applyUrl: "https://www.ltimindtree.com"
  },
  {
    id: "sm-56",
    title: "Applied Scientist - Speech Recognition",
    company: "Amazon",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Improve Alexa's automatic speech recognition (ASR) latency and word-error-rate for heavily accented Indian English. Conduct research and write production code.",
    skills: ["ASR", "Kaldi", "PyTorch", "Python", "C++", "Acoustic Modeling"],
    salaryRange: "₹45,00,000 - ₹60,000,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-14",
    portalSource: "Amazon Jobs",
    applyUrl: "https://amazon.jobs"
  },
  {
    id: "sm-57",
    title: "Junior Data Analyst",
    company: "Genpact",
    location: "Kolkata",
    workType: "WFO",
    description: "Build business intelligence dashboards, perform descriptive statistics on sales data, and prepare data extracts for the advanced analytics team.",
    skills: ["Excel", "Tableau", "SQL", "PowerBI", "Communication"],
    salaryRange: "₹4,50,000 - ₹6,50,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-13",
    portalSource: "Naukri",
    applyUrl: "https://www.genpact.com"
  },
  {
    id: "sm-58",
    title: "Data Engineering Manager",
    company: "Zomato",
    location: "Gurgaon",
    workType: "Hybrid",
    description: "Manage a team of data engineers to scale out real-time streaming pipelines for food delivery tracking and user recommendation graphs.",
    skills: ["Kafka", "Spark", "AWS", "Leadership", "Python"],
    salaryRange: "₹45,00,000 - ₹60,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://www.zomato.com"
  },
  {
    id: "sm-59",
    title: "AI Security Engineer",
    company: "Palo Alto Networks",
    location: "Bangalore",
    workType: "WFO",
    description: "Develop ML-based intrusion detection systems and threat intelligence aggregators. Hardening AI infrastructure against adversarial prompt injections.",
    skills: ["Cybersecurity", "Machine Learning", "Python", "Cloud Security", "Prompt Injection"],
    salaryRange: "₹30,00,000 - ₹45,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-12",
    portalSource: "Company Portal",
    applyUrl: "https://jobs.paloaltonetworks.com"
  },
  {
    id: "sm-60",
    title: "Software Engineer - MLOps",
    company: "CGI",
    location: "Chennai",
    workType: "Hybrid",
    description: "Design automated ML CI/CD pipelines, track model lineage, and manage automated A/B testing of predictive models in production environments.",
    skills: ["MLOps", "Jenkins", "Kubernetes", "Docker", "Python"],
    salaryRange: "₹12,00,000 - ₹18,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "Naukri",
    applyUrl: "https://www.cgi.com"
  },
  {
    id: "sm-61",
    title: "Sr. Deep Learning Researcher",
    company: "Samsung R&D Institute",
    location: "Noida",
    workType: "WFO",
    description: "Conduct fundamental research on edge AI models for mobile devices. Focus on neural architecture search, pruning, and low-latency on-device inference.",
    skills: ["Deep Learning", "TensorFlow Lite", "On-Device AI", "C++", "Research"],
    salaryRange: "₹35,00,000 - ₹50,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-10",
    portalSource: "LinkedIn",
    applyUrl: "https://research.samsung.com/sri-n"
  },
  {
    id: "sm-62",
    title: "Data Analyst II",
    company: "Epsilon",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Analyze large marketing datasets to discover actionable customer segments. Work with the campaign strategy team to measure ROI of hyper-personalized ad delivery.",
    skills: ["SQL", "Tableau", "Marketing Analytics", "Python", "A/B Testing"],
    salaryRange: "₹9,00,000 - ₹14,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-09",
    portalSource: "Indeed India",
    applyUrl: "https://www.epsilon.com"
  },
  {
    id: "sm-63",
    title: "Big Data Architect",
    company: "TCS",
    location: "Trivandrum",
    workType: "WFO",
    description: "Design multi-petabyte data lakes on Azure for banking clients. Provide thought leadership on data governance, security, and scalability.",
    skills: ["Big Data", "Azure Data Factory", "Databricks", "Architecture", "Hadoop"],
    salaryRange: "₹40,00,000 - ₹55,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-14",
    portalSource: "TCS Careers",
    applyUrl: "https://www.tcs.com"
  },
  {
    id: "sm-64",
    title: "NLP Data Scientist",
    company: "Swiggy",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Enhance semantic search for restaurant menus, analyze customer feedback sentiment, and develop intent classification models for automated customer service routing.",
    skills: ["NLP", "Transformers", "Python", "Elasticsearch", "NLTK"],
    salaryRange: "₹25,00,000 - ₹38,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-13",
    portalSource: "LinkedIn",
    applyUrl: "https://careers.swiggy.com"
  },
  {
    id: "sm-65",
    title: "Graduate Engineer Trainee - AI",
    company: "HCLTech",
    location: "Madurai",
    workType: "WFO",
    description: "Join HCL's core engineering group as a trainee. Get hands-on experience by shadowing senior engineers on live ML operations and predictive analytics projects.",
    skills: ["Python", "SQL", "Machine Learning Basics", "Problem Solving"],
    salaryRange: "₹4,00,000 - ₹5,50,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-12",
    portalSource: "Company Portal",
    applyUrl: "https://www.hcltech.com"
  },
  {
    id: "sm-66",
    title: "Principal AI Scientist",
    company: "Microsoft India Development Center",
    location: "Hyderabad",
    workType: "Hybrid",
    description: "Lead cutting-edge research in large language models. Collaborate globally to drive improvements in Azure OpenAI infrastructure and open-source models.",
    skills: ["LLMs", "Research", "PyTorch", "Leadership", "Publications"],
    salaryRange: "₹80,00,000 - ₹1,20,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://careers.microsoft.com"
  },
  {
    id: "sm-67",
    title: "Computer Vision Engineer",
    company: "Karya",
    location: "Remote",
    workType: "Remote",
    description: "Develop robust computer vision pipelines for document layout analysis and OCR tailored for rural mobile captured images.",
    skills: ["Computer Vision", "OCR", "Pytorch", "Python", "Tesseract"],
    salaryRange: "₹18,00,000 - ₹28,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "Instahyre",
    applyUrl: "https://karya.in"
  },
  {
    id: "sm-68",
    title: "GenAI Consultant",
    company: "Accenture",
    location: "Pune",
    workType: "Hybrid",
    description: "Deliver workshops and architect custom Generative AI solutions for enterprise clients in manufacturing and retail domains. Focus on RAG pattern implementation.",
    skills: ["Consulting", "Generative AI", "RAG", "Azure", "Communication"],
    salaryRange: "₹22,00,000 - ₹34,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-10",
    portalSource: "LinkedIn",
    applyUrl: "https://www.accenture.com"
  },
  {
    id: "sm-69",
    title: "Machine Learning Engineer II",
    company: "Dream11",
    location: "Mumbai",
    workType: "WFO",
    description: "Develop personalized match recommendations and optimize player engagement metrics. Build high-throughput scoring systems for live sporting events.",
    skills: ["Machine Learning", "Python", "Spark", "Recommendation Systems", "AWS"],
    salaryRange: "₹30,00,000 - ₹45,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-13",
    portalSource: "LinkedIn",
    applyUrl: "https://dream11.com"
  },
  {
    id: "sm-70",
    title: "AI Product Designer",
    company: "Flipkart",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Design conversational commerce interfaces and intuitive controls for AI-powered shopping features. Synthesize complex AI outputs into simple, human-centric UI constraints.",
    skills: ["UX Design", "Figma", "Conversational AI", "Prototyping", "User Research"],
    salaryRange: "₹25,00,000 - ₹38,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-12",
    portalSource: "Flipkart Careers",
    applyUrl: "https://www.flipkartcareers.com"
  },
  {
    id: "sm-71",
    title: "Data Visualization Specialist",
    company: "Mu Sigma",
    location: "Bangalore",
    workType: "WFO",
    description: "Translate complex machine learning outputs into intuitive dashboards for executive stakeholders using D3.js and Tableau.",
    skills: ["Data Visualization", "D3.js", "Tableau", "Storytelling", "JavaScript"],
    salaryRange: "₹10,00,000 - ₹16,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-10",
    portalSource: "Naukri",
    applyUrl: "https://www.mu-sigma.com"
  },
  {
    id: "sm-72",
    title: "AI Engineer (Recommendation Engines)",
    company: "Myntra",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Design and fine-tune massive-scale collaborative filtering and content-based recommendation systems for fashion e-commerce.",
    skills: ["Recommendation Systems", "Deep Learning", "TensorFlow", "Python", "Data Structure"],
    salaryRange: "₹28,00,000 - ₹40,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-13",
    portalSource: "LinkedIn",
    applyUrl: "https://careers.myntra.com"
  },
  {
    id: "sm-73",
    title: "Chatbot Backend Developer",
    company: "Haptik",
    location: "Mumbai",
    workType: "Remote",
    description: "Develop robust API integrations and webhook handlers to connect advanced GenAI chatbots with internal enterprise ERP and CRM systems.",
    skills: ["Node.js", "Python", "API Development", "Webhook", "MongoDB"],
    salaryRange: "₹12,00,000 - ₹20,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-11",
    portalSource: "Instahyre",
    applyUrl: "https://www.haptik.ai"
  },
  {
    id: "sm-74",
    title: "Speech AI Engineer",
    company: "Descript (India Ops)",
    location: "Remote",
    workType: "Remote",
    description: "Work on advanced audio processing models, noise suppression algorithms, and high-fidelity text-to-speech synthesis networks.",
    skills: ["Audio Processing", "DSP", "PyTorch", "Deep Learning", "Python"],
    salaryRange: "₹40,00,000 - ₹60,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-12",
    portalSource: "LinkedIn",
    applyUrl: "https://www.descript.com"
  },
  {
    id: "sm-75",
    title: "MLOps Engineer Trainee",
    company: "L&T Technology Services",
    location: "Vadodara",
    workType: "WFO",
    description: "Train on enterprise machine learning pipelines. Assist deployments to IoT edge devices in the manufacturing industry under senior guidance.",
    skills: ["Linux", "Python", "Docker", "Git", "Basic ML"],
    salaryRange: "₹4,50,000 - ₹6,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-14",
    portalSource: "Naukri",
    applyUrl: "https://www.ltts.com"
  },
  {
    id: "sm-76",
    title: "Quantitative Researcher (HFT)",
    company: "Tower Research Capital",
    location: "Gurgaon",
    workType: "WFO",
    description: "Develop ultra-low latency trading strategies leveraging advanced statistical modeling and machine learning over terabytes of market tick data.",
    skills: ["Quantitative Research", "C++", "Statistics", "Machine Learning", "Finance"],
    salaryRange: "₹80,00,000 - ₹1,50,00,000",
    experienceLevel: "Senior Level",
    postedDate: "2026-06-10",
    portalSource: "LinkedIn",
    applyUrl: "https://www.tower-research.com"
  },
  {
    id: "sm-77",
    title: "AI Compliance Auditor",
    company: "Deloitte India",
    location: "Hyderabad",
    workType: "Hybrid",
    description: "Audit enterprise GenAI applications for bias, data leakage, and compliance with data privacy laws. Develop risk-mitigation strategies.",
    skills: ["Compliance", "Risk Management", "Data Privacy", "Auditing", "AI Governance"],
    salaryRange: "₹18,00,000 - ₹28,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-14",
    portalSource: "Company Portal",
    applyUrl: "https://www2.deloitte.com/in"
  },
  {
    id: "sm-78",
    title: "Principal ML Engineer - Mapping",
    company: "Ola Electric",
    location: "Bangalore",
    workType: "WFO",
    description: "Lead the deep learning team for spatial-temporal data parsing. Build proprietary highly precise mapping systems using 2-wheeler telemetry.",
    skills: ["GIS", "Spatial Analytics", "Deep Learning", "TensorFlow", "Leadership"],
    salaryRange: "₹50,00,000 - ₹70,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-13",
    portalSource: "LinkedIn",
    applyUrl: "https://olaelectric.com"
  },
  {
    id: "sm-79",
    title: "Data Operations Associate",
    company: "Zepto",
    location: "Mumbai",
    workType: "WFO",
    description: "Maintain data catalog integrity and monitor ETL pipelines. Resolve data anomalies quickly to ensure uninterrupted rapid-delivery operations.",
    skills: ["SQL", "Excel", "Data Operations", "Python", "Monitoring"],
    salaryRange: "₹5,00,000 - ₹8,00,000",
    experienceLevel: "Entry Level",
    postedDate: "2026-06-11",
    portalSource: "Naukri",
    applyUrl: "https://www.zeptonow.com"
  },
  {
    id: "sm-80",
    title: "Staff Data Scientist",
    company: "Postman",
    location: "Bangalore",
    workType: "Hybrid",
    description: "Shape data strategy across different product groups. Analyze high-volume API telemetry to extract new feature insights and improve API security scoring.",
    skills: ["Data Science", "Analytics", "BigQuery", "Python", "API Security"],
    salaryRange: "₹65,00,000 - ₹90,00,000",
    experienceLevel: "Lead / Manager",
    postedDate: "2026-06-14",
    portalSource: "LinkedIn",
    applyUrl: "https://www.postman.com"
  },
  {
    id: "sm-81",
    title: "Generative AI Trainer",
    company: "Simplilearn",
    location: "Remote",
    workType: "Remote",
    description: "Design curriculum and deliver expert-level training sessions on Prompt Engineering, LangChain, and fine-tuning open source models to corporate batches.",
    skills: ["Teaching", "Generative AI", "LangChain", "Communication", "Python"],
    salaryRange: "₹15,00,000 - ₹25,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-12",
    portalSource: "Indeed India",
    applyUrl: "https://www.simplilearn.com"
  },
  {
    id: "sm-82",
    title: "Lead AI Engineer - Gaming",
    company: "Nazara Technologies",
    location: "Mumbai",
    workType: "WFO",
    description: "Develop AI non-player characters (NPCs) with complex behavioral trees and dynamic language models for immersive gaming experiences.",
    skills: ["Game AI", "C++", "Unreal Engine", "Python", "Machine Learning"],
    salaryRange: "₹35,00,000 - ₹50,00,000",
    experienceLevel: "Mid Level",
    postedDate: "2026-06-10",
    portalSource: "LinkedIn",
    applyUrl: "https://www.nazara.com"
  }
];

export const SAMPLE_PROFILES = [
  {
    id: "p-1",
    name: "Aditi Rao",
    role: "Senior AI Researcher",
    organization: "IISc Bangalore",
    location: "Bangalore",
    skills: ["Deep Learning", "Computer Vision", "PyTorch"],
    linkedinUrl: "https://www.linkedin.com/",
    avatarInitials: "AR",
  },
  {
    id: "p-2",
    name: "Vikram Mehta",
    role: "MLOps Architect",
    organization: "Microsoft",
    location: "Hyderabad",
    skills: ["Kubernetes", "Azure", "MLflow", "TensorFlow"],
    linkedinUrl: "https://www.linkedin.com/",
    avatarInitials: "VM",
  },
  {
    id: "p-3",
    name: "Priya Sharma",
    role: "NLP Scientist",
    organization: "AI4Bharat",
    location: "Chennai",
    skills: ["NLP", "Transformers", "Indic Languages"],
    linkedinUrl: "https://www.linkedin.com/",
    avatarInitials: "PS",
  },
  {
    id: "p-4",
    name: "Rohan Gupta",
    role: "Lead Data Scientist",
    organization: "Swiggy",
    location: "Bangalore",
    skills: ["Predictive Modeling", "Spark", "Python"],
    linkedinUrl: "https://www.linkedin.com/",
    avatarInitials: "RG",
  },
  {
    id: "p-5",
    name: "Sneha Reddy",
    role: "Applied Scientist",
    organization: "Amazon Web Services",
    location: "Hyderabad",
    skills: ["Recommendation Systems", "Deep Learning"],
    linkedinUrl: "https://www.linkedin.com/",
    avatarInitials: "SR",
  }
];

export const SAMPLE_RESEARCH_OPENINGS = [
  {
    id: "ro-1",
    title: "Junior Research Fellow (JRF): Trustworthy AI",
    institution: "IIT Bombay",
    location: "Mumbai",
    department: "Computer Science",
    focusArea: "Robustness and fairness in large language models",
    stipend: "₹37,000 / month + HRA",
    deadline: "2026-08-15",
    applyUrl: "https://www.iitb.ac.in",
    eligibility: "B.Tech/B.E in CS/IT or MCA. Fresh graduates eligible."
  },
  {
    id: "ro-2",
    title: "Project Associate I: Edge AI for IoT",
    institution: "IISc Bangalore",
    location: "Bangalore",
    department: "Electrical Engineering",
    focusArea: "Deploying lightweight ML models on edge microcontroller units",
    stipend: "₹31,000 / month + HRA",
    deadline: "2026-07-30",
    applyUrl: "https://www.iisc.ac.in",
    eligibility: "Recent B.Tech/M.Sc graduates in EE/ECE/CS."
  },
  {
    id: "ro-3",
    title: "Research Assistant: Multimodal ML",
    institution: "IIIT Hyderabad",
    location: "Hyderabad",
    department: "Cognitive Science Lab",
    focusArea: "Building models to detect emotion from audio-visual signals",
    stipend: "₹25,000 / month",
    deadline: "2026-07-10",
    applyUrl: "https://www.iiit.ac.in",
    eligibility: "B.Tech/BE Graduates (2025/2026 Batch) with Python skills."
  },
  {
    id: "ro-4",
    title: "Pre-Doctoral Researcher: GenAI in Healthcare",
    institution: "AIIMS Delhi & IIT Delhi",
    location: "Delhi NCR",
    department: "Joint Research Hub",
    focusArea: "Medical image segmentation for early cancer detection",
    stipend: "₹40,000 / month",
    deadline: "2026-08-01",
    applyUrl: "https://www.iitd.ac.in",
    eligibility: "B.Tech/Masters graduates planning to pursue a Ph.D. later."
  }
];

export const SAMPLE_COURSES = [
  {
    id: "c-1",
    title: "Machine Learning (NPTEL)",
    provider: "IIT Madras / NPTEL",
    duration: "12 Weeks",
    level: "Intermediate",
    skills: ["Python", "Supervised Learning", "Neural Networks"],
    url: "https://nptel.ac.in/",
    certType: "Govt. Free Certification (Exam fee separate)",
  },
  {
    id: "c-2",
    title: "Google Cloud Computing Foundations",
    provider: "Google Cloud / NASSCOM",
    duration: "40 Hours",
    level: "Beginner",
    skills: ["Cloud Basics", "GCP", "Big Data", "ML"],
    url: "https://cloudskillsboost.google/",
    certType: "100% Free Certification",
  },
  {
    id: "c-3",
    title: "CS50's Introduction to Computer Science",
    provider: "Harvard University / edX",
    duration: "12 Weeks",
    level: "Beginner",
    skills: ["C", "Python", "SQL", "Algorithms", "Data Structures"],
    url: "https://pll.harvard.edu/course/cs50-introduction-computer-science",
    certType: "Free Audit (Certificate Paid)",
  },
  {
    id: "c-4",
    title: "Machine Learning Specialization",
    provider: "Stanford / DeepLearning.AI",
    duration: "2 Months",
    level: "Beginner / Intermediate",
    skills: ["Python", "Machine Learning", "Neural Networks", "TensorFlow"],
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    certType: "Free Audit Available",
  },
  {
    id: "c-5",
    title: "Elements of AI",
    provider: "University of Helsinki",
    duration: "6 Weeks",
    level: "Beginner",
    skills: ["AI Basics", "Machine Learning", "Neural Networks"],
    url: "https://www.elementsofai.com/",
    certType: "Free Certification",
  },
  {
    id: "c-6",
    title: "AWS Machine Learning Foundations",
    provider: "AWS Training & Certification",
    duration: "Self-paced",
    level: "Beginner",
    skills: ["AWS", "Machine Learning", "Cloud"],
    url: "https://explore.skillbuilder.aws/learn",
    certType: "Free Certification",
  },
  {
    id: "c-7",
    title: "Scientific Computing with Python",
    provider: "freeCodeCamp",
    duration: "300 Hours",
    level: "Beginner",
    skills: ["Python", "Data Structures", "Algorithms"],
    url: "https://www.freecodecamp.org/learn/scientific-computing-with-python/",
    certType: "100% Free Certification",
  },
  {
    id: "c-8",
    title: "Data Science Professional Certificate",
    provider: "IBM / Coursera",
    duration: "5 Months",
    level: "Beginner",
    skills: ["Python", "SQL", "Data Analysis", "Machine Learning"],
    url: "https://www.coursera.org/professional-certificates/ibm-data-science",
    certType: "Free Audit Available",
  }
];

export const SAMPLE_NEWS = [
  {
    id: "n-1",
    title: "OpenAI Unveils GPT-5: A Leap Towards AGI?",
    date: "2026-06-12",
    source: "TechCrunch",
    summary: "OpenAI's latest iteration of its flagship model promises near-human reasoning across multiple domains, sparking debates around the timeline of Artificial General Intelligence (AGI).",
    linkedinTemplate: "Exciting times in the world of AI! 🚀 OpenAI just announced GPT-5, revealing major leaps in multi-domain reasoning. The line between specialized AI and AGI is getting blurrier every day. What are your thoughts on the new capabilities?\n\n#AI #MachineLearning #OpenAI #AGI #TechTrends"
  },
  {
    id: "n-2",
    title: "Google DeepMind's AlphaFold 4 Revolutionizes Drug Discovery",
    date: "2026-06-10",
    source: "Nature",
    summary: "The newest version of AlphaFold maps complex protein-ligand interactions with unprecedented accuracy, cutting early-stage drug discovery timelines by years.",
    linkedinTemplate: "Generative AI isn't just about language—it's reshaping biology! 🧬 Google DeepMind's AlphaFold 4 is now predicting complex protein-ligand interactions with incredible accuracy, potentially shaving years off drug development timelines. A massive win for interdisciplinary ML!\n\n#DeepMind #AlphaFold #AIinHealthcare #MachineLearning #Biotech"
  },
  {
    id: "n-3",
    title: "EU AI Act Implementation Shows Early Market Shifts",
    date: "2026-06-08",
    source: "Bloomberg",
    summary: "With the full enforcement of the EU AI Act underway, tech giants are rapidly restructuring their foundation models for strict compliance, prioritizing explainability and auditing.",
    linkedinTemplate: "Regulation is shaping the next era of AI. ⚖️ As the EU AI Act enforces stricter auditing and explainability requirements, we are seeing a massive shift towards \"Transparent AI\". Companies that prioritize Responsible AI are going to lead the market.\n\n#ResponsibleAI #EUAIAct #AICompliance #MachineLearning"
  },
  {
    id: "n-4",
    title: "Small Language Models (SLMs) Overtake LLMs in Enterprise Adoption",
    date: "2026-06-05",
    source: "Forbes",
    summary: "Due to cost-efficiency and localized privacy, enterprises are pivoting from massive APIs to open-source Small Language Models running on private cloud infrastructure.",
    linkedinTemplate: "Bigger isn't always better. 📉 We are seeing a massive enterprise shift towards Small Language Models (SLMs) deployed on private infrastructure. The focus is shifting from \"raw parameters\" to \"efficiency, cost, and data privacy\". Highly optimized, specialized models are the future of enterprise ML.\n\n#SLM #LLM #EnterpriseAI #DataPrivacy #MachineLearning"
  }
];

export const CITIES_CONCENTRATED = [
  "Bangalore",
  "Kochi",
  "Mumbai",
  "Delhi NCR",
  "Gurgaon",
  "Noida",
  "Chennai",
  "Hyderabad",
  "Pune",
  "Kolkata",
  "Trivandrum",
  "Madurai",
  "Vadodara",
  "Remote"
];
